Added -o output directory version->1.105

diff --git a/gentoo-utils/7zSubComp/7zSubComp b/gentoo-utils/7zSubComp/7zSubComp
--- a/gentoo-utils/7zSubComp/7zSubComp
+++ b/gentoo-utils/7zSubComp/7zSubComp
@@ -1,6 +1,6 @@
 #!/bin/bash
 # 7zip subdirectory compressor and subdirectory archive extractor.
-RELEASE_VERSION="1.01"
+RELEASE_VERSION="1.105"
 
 # Color definitions
 RED='\033[0;31m'
@@ -16,6 +16,9 @@ MEMFREE=$(echo "$MEMFREE * 7/10" | bc)
 if [[ 1 = $(echo "$MEMFREE > 2048" | bc) ]] 
 then
 	ZSTD_EXTRACT_MEMFREE="2048MiB"
+elif [[ 1 = $(echo "$MEMFREE < 128" | bc) ]]
+then
+	ZSTD_EXTRACT_MEMFREE="128MiB"
 else
 	ZSTD_EXTRACT_MEMFREE=$MEMFREE
 	ZSTD_EXTRACT_MEMFREE+="MiB"
@@ -131,32 +134,59 @@ print_archives()
 
 print_subdirectories()
 {
-	[[ -n $(ls -dp1 * | grep /) ]] &&
+	[[ -n $(ls -1Ap | grep /) ]] &&
 		echo -e "\n\t${NOC}Subdirectories${BLUE}\n" && ls -d1 */
 }
 
-show_master_path()
+show_output_directory()
 {
+	[[ $OUTPUT_PATH != $MASTER_PATH ]] && 
+		echo -e "\n${CYAN}Output directory set to: \"${NOC}$OUTPUT_PATH${CYAN}\"${NOC}"
+}
+
+show_path()
+# $1 = archives
+# $2 = subdirectories
+# $3 = option
+{
+	old_wd=$(pwd)
 	echo -ne "${BLUE}"
-	case $1 in
+	case $3 in
 		ARCHIVES)
+			cd "$1"
 			print_archives
+			echo -ne "\n${NOC}$1\t"
+			SIZE_ARCHIVES=$(du -bsc "$1"/ | grep total | cut -f1)
+			accurate_sizeof $SIZE_ARCHIVES
 		;;
-		SUBDIRS)	
+		SUBDIRS)
+			cd "$2"
 			print_subdirectories
+			echo -ne "\n${NOC}$2\t"
+			SIZE_SUBDIR=$(du -bsc "$2"/ | grep total | cut -f1)
+			accurate_sizeof $SIZE_SUBDIR
 		;;
 		ALL)
+			cd "$1"
 			print_archives
+			if [[ $2 != $1 ]]
+			then
+				echo -ne "\n${NOC}$1\t"
+				SIZE_ARCHIVES=$(du -bsc "$1"/ | grep total | cut -f1)
+				accurate_sizeof $SIZE_ARCHIVES
+			fi
+			cd "$2"
 			print_subdirectories
+			echo -ne "\n${NOC}$2\t"
+			SIZE_SUBDIR=$(du -bsc "$2"/ | grep total | cut -f1)
+			accurate_sizeof $SIZE_SUBDIR
 		;;
-	esac	
-
-	echo -ne "\n${NOC}$MASTER_PATH\t"
-	SIZE_MASTER=$(du -bsc "$MASTER_PATH"/ | grep total | cut -f1)
-	accurate_sizeof $SIZE_MASTER
+	esac		
+	cd "$old_wd"
 }
 
 check_exit_status()
+# $1 = exit status option
 {
 	exitCode=$?
 	if [[ 0 != $exitCode ]];
@@ -179,21 +209,40 @@ check_exit_status()
 	fi
 }
 
+path_is_valid()
+# $1 = path to check
+{
+	old_wd=$(pwd)
+	cd "$1"
+	check_exit_status PATH
+	cd "$old_wd"
+}
+
+check_output_path()
+{
+	old_wd=$(pwd)
+	if [[ -n $OUTPUT_PATH ]]
+	then
+		cd "$OUTPUT_PATH"
+		check_exit_status PATH
+		OUTPUT_PATH=$(pwd)
+	else
+		[[ -n $MASTER_PATH ]] && OUTPUT_PATH=$MASTER_PATH
+	fi
+	cd "$old_wd"
+}
+
 check_master_path()
 {
-	if [[ -d $MASTER_PATH ]]
+	old_wd=$(pwd)
+	if [[ -n $MASTER_PATH ]]
 	then
-		if [[ -n $(echo $MASTER_PATH | cut -c 1 | grep /) ]]
-		then
-			cd "$MASTER_PATH"
-		else cd "$(pwd)/$MASTER_PATH"
-		fi
+		cd "$MASTER_PATH"
 		check_exit_status PATH
 		MASTER_PATH=$(pwd)
-		show_master_path $1
-	else
-		echo -e "${RED}That directory does not exist.${NOC}" && exit 1
 	fi
+	cd "$old_wd"
+	check_output_path
 }
 
 bar()
@@ -220,8 +269,13 @@ close_info_header()
 }
 
 print_info()
+# $1 = archives
+# $2 = subdirectories
+# $3 = verb
 {
+	old_wd=$(pwd)
 	SIZE_ARCHIVES=0
+	cd "$1"
 	if [[ -n $(ls -1 | egrep ".7z|.zip|.rar|.tar.zst") ]]
 	then
 		[[ -n $(ls -1 | grep ".7z") ]] && 
@@ -234,7 +288,8 @@ print_info()
 			SIZE_ARCHIVES=$(echo "$(du -bc *.tar.zst | grep total | cut -f1) + $SIZE_ARCHIVES" | bc -l)
 	fi
 	
-	if [[ -n $(ls -dp1 * | grep /) ]]
+	cd "$2"
+	if [[ -n $(ls -1Ap | grep /) ]]
 	then
 		SIZE_SUBDIR=$(du -bc */ | grep total | cut -f1)
 	else
@@ -242,6 +297,7 @@ print_info()
 	fi
 	
 	SIZE_MASTER=$(du -bsc "$MASTER_PATH"/ | grep total | cut -f1)
+	SIZE_OUTPUT=$(du -bsc "$OUTPUT_PATH"/ | grep total | cut -f1)
 
 	echo -ne "${CYAN}subdirectories size\t\t\t:\t${NOC}"
 	accurate_sizeof $SIZE_SUBDIR
@@ -249,7 +305,7 @@ print_info()
 	echo -ne "${CYAN}archives size\t\t\t\t:\t${NOC}"
 	accurate_sizeof $SIZE_ARCHIVES
 
-	case $1 in
+	case $3 in
 		REMOVE)
 			echo -ne "${CYAN}master directory size before\t\t:\t${NOC}"
 			accurate_sizeof $SIZE_ORIG_MASTER
@@ -264,9 +320,15 @@ print_info()
 			echo -ne "${CYAN}(archives - subdirectories)\t\t:\t${NOC}"
 			accurate_sizeof $SIZE_DELTA
 			echo -ne "${CYAN}master directory size\t\t\t:\t${NOC}"
-			accurate_sizeof $SIZE_MASTER	
+			accurate_sizeof $SIZE_MASTER
+			if [[ $MASTER_PATH != $OUTPUT_PATH ]]
+			then
+				echo -ne "${CYAN}output directory size\t\t\t:\t${NOC}"
+				accurate_sizeof $SIZE_OUTPUT
+			fi
 		;;
 	esac
+	cd "$old_wd"
 }
 
 check_illegal_chars()
@@ -277,7 +339,7 @@ check_illegal_chars()
 	for ((char_i = 0 ; char_i < $str_len - 1 ; char_i++ )); do 
 		c=${MYVAR:$char_i:1}
 		case $c in
-			'['|']') # grep hates these chars
+			'['|']')
 				ILLEGAL+=$c
 			;;
 		esac
@@ -291,11 +353,12 @@ check_illegal_chars()
 }
 
 check_archives()
+# $1 = archives
 {
+	cd "$1"
 	b=1
 	while [[ 1 = $(echo "$b <= $TARGETS_NO" | bc) ]];
 	do
-		cd "$MASTER_PATH"
 		SED_EXP=$b'p'
 		x=$(ls -1 | egrep ".7z|.zip|.rar|.tar.zst" | sed -n "$SED_EXP")	
 		check_illegal_chars "$x"
@@ -304,55 +367,100 @@ check_archives()
 	[[ -n $ILLEGAL_EXIT ]] && exit 1
 }
 
-if [[ -n $2 ]] 
-then
-	case $2 in
+check_arg()
+# $1 = argument 
+{
+	[[ -z $1 ]] && return
+	case $1 in
 		"y"|"-y"|"--yes")
-			[[ -n $3 ]] && MASTER_PATH=$3
 			YES_ALL=1
 		;;
+		"o"|"-o")
+			OUTPUT_FLAG=1
+		;;
+		"x"|"-x"|"-x="*|\
+		"e"|"-e"|"-e="*|"--extract="*|\
+		"-c="*|"--compress="*|\
+		"v"|"-v"|"--view"|\
+		"r"|"-r"|"--remove")
+			MASTER_FLAG=1 
+		;;
 		*)
-			MASTER_PATH=$2
+			if [[ 1 = $OUTPUT_FLAG ]]
+			then
+				path_is_valid $1
+				OUTPUT_PATH=$1
+				OUTPUT_FLAG=0
+			elif [[ 1 = $MASTER_FLAG ]]
+			then
+				path_is_valid $1
+				MASTER_PATH=$1
+				MASTER_FLAG=0
+			else
+				case $1 in
+					"h"|"-h"|"-help"|"--help")
+					;;
+					*)
+						echo -e "${RED}\"${NOC}$1${RED}\" is invalid input.${NOC}"
+						exit 1
+					;;
+				esac
+			fi
 		;;
 	esac
-fi
+}
+
+# check arguments or $(1..9)
+check_arg $1
+check_arg $2
+check_arg $3
+check_arg $4
+check_arg $5
+check_arg $6
+check_arg $7
+check_arg $8
+check_arg $9
+check_master_path
 
 case $1 in
     "h"|"-h"|"-help"|"--help")
-        echo -e "${CYAN}7zSubComp ${BLUE}[ [ -c=${NOC}{type}${BLUE} ] [-e -e=${NOC}{type}${BLUE} ] -r -v ] [ -y ] [directory A]${NOC}"
+        echo -e "${CYAN}7zSubComp ${BLUE}[ [ -c=${NOC}{type}${BLUE} ] [-e -e=${NOC}{type}${BLUE} ] -r -v ] [directory A] [ -o ] [directory B] [ -y ]${NOC}"
         echo -e "Release version: $RELEASE_VERSION"
 	echo
         echo -e "7z/zstd subdirectory compressor and 7z/zip/rar/zstd archive extractor."
         echo
         echo -e "Compressing"
-        echo -e "   ${BLUE}-c=${NOC}{type}${BLUE} --compress=${NOC}{type}${NOC}    -   enter directory A to compress all subdirectories of A into new archives in A."
+        echo -e "   ${BLUE}-c=${NOC}{type}${BLUE} --compress=${NOC}{type}${NOC}    -   Enter directory A to compress all subdirectories of A into new archives in A."
         echo    "   type={ 7z, zstd }                  Verifies archive integrity after each archive creation."
         echo
         echo -e "Decompressing"
-        echo -e "   ${BLUE}-e --extract${NOC}                  -   enter directory A to extract all archives of A into subdirectories in A."
-        echo -e "   ${BLUE}-e=${NOC}{type}${BLUE} --extract=${NOC}{type}        Extract only one type with \"-e={type}\" or \"--extract={type}\" ."
+        echo -e "   ${BLUE}-e --extract -x${NOC}                        -   Enter directory A to extract all archives of A into subdirectories in A."
+        echo -e "   ${BLUE}-x=${NOC}{type}${BLUE} -e=${NOC}{type}${BLUE} --extract=${NOC}{type}   -   Extract only {type}."
         echo    "   type={ 7z, zip, rar, zstd }"
         echo
         echo -e "Removing"
-        echo -e "   ${BLUE}-r --remove${NOC}             -   enter directory A to remove only subdirectories under A."
+        echo -e "   ${BLUE}-r --remove${NOC}             -   Enter directory A to remove only subdirectories under A."
         echo
         echo    "Viewing"
-        echo -e "   ${BLUE}-v --view${NOC}               -   enter directory A to view size info and all subdirectories and archives of A."
+        echo -e "   ${BLUE}-v --view${NOC}               -   Enter directory A to view size info and all subdirectories and archives of A."
         echo
         echo    "Other"
-        echo -e "   ${BLUE}-y --yes${NOC}                -   confirm without asking."
+        echo -e "   ${BLUE}-y --yes${NOC}                -   Confirm without asking."
+		echo -e "   ${BLUE}-o ${NOC}{directory B}        -   Set the output directory for compressing or extracting to directory B."
         echo
         echo -e "Examples:"
         echo        
-        echo -e "   7zSubComp -c=7z .       -   Compress all subdirectories under current directory \".\" into 7z archives."
+        echo -e "   7zSubComp -c=7z .             -   Compress all subdirectories under current directory \".\" into 7z archives."
+        echo -e "   7zSubComp -c=7z . -o ~/test   -   Compress all subdirectories under current directory \".\" into 7z archives inside \"~/test\"."
         echo
-        echo -e "   7zSubComp -e .          -   Extract all archives under current directory \".\" ."
-        echo -e "   7zSubComp -e=zstd .     -   Extract all zstd archives under current directory \".\" ."
+        echo -e "   7zSubComp -e .                -   Extract all archives under current directory \".\" ."
+        echo -e "   7zSubComp -e=zstd .           -   Extract all zstd archives under current directory \".\" ."
+        echo -e "   7zSubComp -x . -o ~/test      -   Extract all archives under current directory \".\" to \"~/test\"."
         echo 
-        echo -e "   7zSubComp -r -y .       -   Remove only subdirectories under current directory \".\""
-        echo -e "                               without asking for confirmation. With \"7zSubComp -r -y\" it will still ask once."
+        echo -e "   7zSubComp -r -y .             -   Remove only subdirectories under current directory \".\""
+        echo -e "                                     without asking for confirmation. With \"7zSubComp -r -y\" it will still ask once."
         echo
-        echo -e "   7zSubComp -v .          -   View subdirectories and archives under current directory \".\" ."
+        echo -e "   7zSubComp -v .                -   View subdirectories and archives under current directory \".\" ."
         echo
         echo -e "   \".\" above can be replaced with any directory. Not providing one will ask you for one."
         echo
@@ -364,10 +472,11 @@ case $1 in
 			echo
 			read -e -p ': ' MASTER_PATH	
 		fi
-		check_master_path ALL
+		check_master_path
+		show_path $MASTER_PATH $MASTER_PATH ALL
 
 		begin_info_header
-		print_info
+		print_info $MASTER_PATH $MASTER_PATH
 		close_info_header
 	;;
 	"r"|"-r"|"--remove")
@@ -378,11 +487,11 @@ case $1 in
 			echo
 			read -e -p ': ' MASTER_PATH
 		fi	
-		
-		check_master_path ALL
+		check_master_path
+		show_path $MASTER_PATH $MASTER_PATH ALL
 
-		[[ -n $(ls -dp1 * | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
-		[[ -z $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to remove.${NOC}" && exit
+		[[ -n $(ls -1Ap | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
+		[[ -z $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"${NOC}$MASTER_PATH${RED}\" to remove.${NOC}" && exit
 
 		echo -e "\n${GREEN}$TARGETS_NO${CYAN} target subdirectories found."	
 		
@@ -411,14 +520,18 @@ case $1 in
 				done
 			fi
 		fi
-		show_master_path ALL
+		
+		show_path $MASTER_PATH $MASTER_PATH ALL
 	
 		begin_info_header
 		echo -e "${GREEN}$TARGETS_NO${CYAN} subdirectories removed in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
-		print_info REMOVE
+		print_info $MASTER_PATH $MASTER_PATH REMOVE
 		close_info_header
 	;;
-	"e"|"-e"|"--extract"|"-e=7z"|"-e=zip"|"-e=rar"|"-e=zstd"|"--extract=7z"|"--extract=zip"|"--extract=rar"|"--extract=zstd") 
+	"x"|"-x"|"-x=7z"|"-x=zip"|"-x=rar"|"-x=zstd"|\
+	"e"|"-e"|"--extract"|\
+	"-e=7z"|"-e=zip"|"-e=rar"|"-e=zstd"|\
+	"--extract=7z"|"--extract=zip"|"--extract=rar"|"--extract=zstd") 
 		if [[ $1 =~ "=" ]] 
 		then
 			EXTRACT_TYPE=$(echo $1 | cut -d'=' -f2)
@@ -432,26 +545,44 @@ case $1 in
 			echo
 			read -e -p ': ' MASTER_PATH
 		fi
+		check_master_path
+		show_path $MASTER_PATH $OUTPUT_PATH ALL
 
-		check_master_path ALL
 		TARGETS_NO=0
-		
-		[[ -n $(ls -1 | egrep ".7z") && "ALL" == $EXTRACT_TYPE || "7z" == $EXTRACT_TYPE ]] && 
-			TARGETS_NO=$(ls -1 *.7z | wc -l)
-		[[ -n $(ls -1 | egrep ".zip") && "ALL" == $EXTRACT_TYPE || "zip" == $EXTRACT_TYPE ]] && 
-			TARGETS_NO=$(echo "$(ls -1 *.zip | wc -l) + $TARGETS_NO" | bc -l)
-		[[ -n $(ls -1 | egrep ".rar") && "ALL" == $EXTRACT_TYPE || "rar" == $EXTRACT_TYPE ]] && 
-			TARGETS_NO=$(echo "$(ls -1 *.rar | wc -l) + $TARGETS_NO" | bc -l)
-		[[ -n $(ls -1 | egrep ".tar.zst") && "ALL" == $EXTRACT_TYPE || "zstd" == $EXTRACT_TYPE ]] && 
-			TARGETS_NO=$(echo "$(ls -1 *.tar.zst | wc -l) + $TARGETS_NO" | bc -l)
-		[[ -z $TARGETS_NO ]] && echo -e "${RED}No archives found inside \"$MASTER_PATH\" to extract.${NOC}" && exit
+		cd "$MASTER_PATH"
+		if [[ -n $(ls -1 | egrep ".7z") ]] 
+		then 
+			if [[ "ALL" == $EXTRACT_TYPE || "7z" == $EXTRACT_TYPE ]]
+			then TARGETS_NO=$(echo "$(ls -1 *.7z | wc -l) + $TARGETS_NO" | bc -l)
+			fi
+		elif [[ -n $(ls -1 | egrep ".zip") ]]
+		then 
+			if [["ALL" == $EXTRACT_TYPE || "zip" == $EXTRACT_TYPE ]]
+			then TARGETS_NO=$(echo "$(ls -1 *.zip | wc -l) + $TARGETS_NO" | bc -l)
+			fi
+		elif [[ -n $(ls -1 | egrep ".rar") ]] 
+		then
+			if [[ "ALL" == $EXTRACT_TYPE || "rar" == $EXTRACT_TYPE ]]
+			then TARGETS_NO=$(echo "$(ls -1 *.rar | wc -l) + $TARGETS_NO" | bc -l) 
+			fi
+		elif [[ -n $(ls -1 | egrep ".tar.zst") ]]
+		then 
+			if [[ "ALL" == $EXTRACT_TYPE || "zstd" == $EXTRACT_TYPE ]]
+			then TARGETS_NO=$(echo "$(ls -1 *.tar.zst | wc -l) + $TARGETS_NO" | bc -l)
+			fi
+		fi
+		[[ 0 = $TARGETS_NO ]] && echo -e "${RED}No $EXTRACT_TYPE archives found inside \"$MASTER_PATH\" to extract.${NOC}" && exit	
 		
 		EXT_EXP=".7z|.zip|.rar|.tar.zst"
 		[[ "ALL" != $EXTRACT_TYPE ]] && EXT_EXP=$EXTRACT_TYPE
 		[[ "zstd" = $EXTRACT_TYPE ]] && EXT_EXP=".tar.zst"
 
 		echo -e "\n${GREEN}$TARGETS_NO${NOC} target archives found."
-		check_archives
+		
+		check_archives $MASTERPATH
+		show_output_directory
+
+		cd "$OUTPUT_PATH"
 		OVERWRITE_FLAG=0
 		if [[ -z $YES_ALL ]] 
 		then
@@ -473,10 +604,10 @@ case $1 in
 			while [[ 1 = $(echo "$i <= $TARGETS_NO" | bc) ]];
 			do
 				SED_EXP=$i'p'
-				x=$(ls -1 | egrep $EXT_EXP | sed -n "$SED_EXP")
+				x=$(ls -1 $MASTER_PATH | egrep $EXT_EXP | sed -n "$SED_EXP")
 				
 				echo -ne "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]\t$x\t${NOC}"
-				file_size=$(du -bs * | grep "$x")
+				file_size=$(du -bs "$MASTER_PATH/$x")
 				accurate_sizeof $file_size
 				
 				dot_i=${x//[^.]}
@@ -509,7 +640,7 @@ case $1 in
 				
 				EXTRACT_FLAG=0
 				# check if "$abs_name"/ size of all files is >= archive file.
-				if [[ 1 = $(echo "$(echo "$(du -bc . | grep total | cut -f1) - 4096" | bc) >= $(du -b "../$x" | cut -f1)" | bc) ]]
+				if [[ 1 = $(echo "$(echo "$(du -bc "$OUTPUT_PATH/$abs_name/" | grep total | cut -f1) - 4096" | bc) >= $(du -b "$MASTER_PATH/$x" | cut -f1)" | bc) ]]
 				then
 					if [[ 0 = $OVERWRITE_FLAG ]]
 					then
@@ -544,13 +675,13 @@ case $1 in
 					fi
 				fi
 				
-				cd "$MASTER_PATH"
+				cd "$OUTPUT_PATH"
 				((i++))
 			done
 			
 			begin_info_header
 			echo -e "${GREEN}$TARGETS_NO${CYAN} archives extracted in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
-			print_info
+			print_info $MASTER_PATH $OUTPUT_PATH
 			close_info_header
 		fi		
 	;;	  
@@ -563,25 +694,28 @@ case $1 in
 			echo
 			read -e -p ': ' MASTER_PATH
 		fi
+		check_master_path
+		show_path $OUTPUT_PATH $MASTER_PATH ALL
 
+		cd "$MASTER_PATH"
 		OVERWRITE_FLAG=0
-		check_master_path ALL
-		[[ -n $(ls -dp1 * | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
-		[[ -z $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to compress.${NOC}" && exit
+		[[ -n $(ls -1Ap | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
+		[[ 0 = $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to compress.${NOC}" && exit
 
 		echo -e "\n${GREEN}$TARGETS_NO${NOC} target subdirectories found."
 		
 		[[ 7z = $COMPRESS_TYPE ]] && echo -e "\n${CYAN}Current 7z compression settings: ${NOC}$DEFAULT_7zCOMPRESS_EXP"
 		[[ zstd = $COMPRESS_TYPE ]] && echo -e "\n${CYAN}Current zstd compression settings: ${NOC}$DEFAULT_ZSTDCOMPRESS_EXP"
-		
+		show_output_directory
+
 		if [[ -z $YES_ALL ]] 
 		then
 			case $COMPRESS_TYPE in
 				7z)
-					[[ -z $(ls -A * | egrep ".7z") ]] && NEW_WRITE=0
+					[[ -z $(ls -A "$OUTPUT_PATH/" | egrep ".7z") ]] && NEW_WRITE=0
 				;;
 				zstd)
-					[[ -z $(ls -A * | egrep ".tar.zst") ]] && NEW_WRITE=0
+					[[ -z $(ls -A "$OUTPUT_PATH/" | egrep ".tar.zst") ]] && NEW_WRITE=0
 				;;
 			esac
 			if [[ -z $NEW_WRITE ]] 
@@ -603,21 +737,21 @@ case $1 in
 			do
 				COMPRESS_FLAG=0
 				SED_EXP=$i'p'
-				x=$(ls -d1 */ | sed -n "$SED_EXP")
+				x=$(ls -1Ap "$MASTER_PATH" | grep / | sed -n "$SED_EXP")
 				x=${x::-1}
 				
 				echo -ne "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]\t$x\t${NOC}"
-				accurate_sizeof $(du -bs "$x"/ | cut -f1)
+				accurate_sizeof $(du -bs "$MASTER_PATH/$x"/ | cut -f1)
 
 				# check for existing archives
 				case $COMPRESS_TYPE in
 					7z)
-						if [[ -e "$x.7z" ]]
+						if [[ -e "$OUTPUT_PATH/$x.7z" ]]
 						then
 							if [[ 0 = $OVERWRITE_FLAG ]]
 							then
 								echo -e "${CYAN}Deleting old 7z archive...${NOC}"
-								rm -v "$x.7z"
+								rm -v "$OUTPUT_PATH/$x.7z"
 								echo
 							else
 								COMPRESS_FLAG=1
@@ -625,12 +759,12 @@ case $1 in
 						fi
 					;;
 					zstd)
-						if [[ -e "$x.tar.zst" ]]
+						if [[ -e "$OUTPUT_PATH/$x.tar.zst" ]]
 						then
 							if [[ 0 = $OVERWRITE_FLAG ]]
 							then
 								echo -e "${CYAN}Deleting old zstd archive...${NOC}"
-								rm -v "$x.tar.zst"
+								rm -v "$OUTPUT_PATH/$x.tar.zst"
 								echo
 							else
 								COMPRESS_FLAG=1
@@ -644,11 +778,11 @@ case $1 in
 					case $COMPRESS_TYPE in
 						7z)
 							echo -e "${CYAN}Creating new 7z archive...${NOC}"
-							COMPRESS_EXP="$DEFAULT_7zCOMPRESS_EXP \"$x.7z\" \"$x\"/"
+							COMPRESS_EXP="$DEFAULT_7zCOMPRESS_EXP \"$OUTPUT_PATH/$x.7z\" \"$x\"/"
 						;;
 						zstd)
 							echo -e "${CYAN}Creating new zstd archive...${NOC}"
-							COMPRESS_EXP="$DEFAULT_ZSTDCOMPRESS_EXP \"$x.tar.zst\" \"$x\"/"
+							COMPRESS_EXP="$DEFAULT_ZSTDCOMPRESS_EXP \"$OUTPUT_PATH/$x.tar.zst\" \"$x\"/"
 						;;
 						*)
 							exit 1
@@ -662,10 +796,10 @@ case $1 in
 					echo -e "\n${CYAN}Verifying integrity of archive...${NOC}"
 					case $COMPRESS_TYPE in
 						7z)
-							INTEGRITY_EXP="7z t \"$x.7z\""
+							INTEGRITY_EXP="7z t \"$OUTPUT_PATH/$x.7z\""
 						;;
 						zstd)
-							INTEGRITY_EXP="zstd --test \"$x.tar.zst\""
+							INTEGRITY_EXP="zstd --test \"$OUTPUT_PATH/$x.tar.zst\""
 						;;
 					esac
 
@@ -680,7 +814,7 @@ case $1 in
 
 			begin_info_header
 			echo -e "${GREEN}$TARGETS_NO${CYAN} archives created and verified in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
-			print_info
+			print_info $OUTPUT_PATH $MASTER_PATH
 			close_info_header
 		fi
 	;;
