modified:   7zSubComp

diff --git a/gentoo-utils/7zSubComp/7zSubComp b/gentoo-utils/7zSubComp/7zSubComp
--- a/gentoo-utils/7zSubComp/7zSubComp
+++ b/gentoo-utils/7zSubComp/7zSubComp
@@ -3,7 +3,7 @@
 # 7zip subdirectory compressor and subdirectory archive extractor.
 # 
 #   -c --compress           -   enter directory A to compress all subdirectories of A into new archives in A. 
-#                               Checks archive integrity after creation.
+#                               Verifies archive integrity after creation.
 #   -x -e --extract         -   enter directory A to extract all archives of A into subdirectories in A.
 #   -r --remove             -   enter directory A to remove all subdirectories of A but save the archives.
 #   -v --view               -   enter directory A to view all subdirectories and archives of it.
@@ -16,16 +16,28 @@ BLUE='\033[0;34m'
 CYAN='\033[00;36m'
 NOC='\033[0m'
 
+# options used to compress
+DEFAULT_COMPRESS_EXP="7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "
+
 accurate_sizeof()
 # $1 = bytes input
 {
-	if [[ 1 == $(echo "($1 / 10^12) >= 1" | bc -l) ]]; then
+	if [[ 1 = $(echo "$1 < 0" | bc) ]] 
+	then
+		val=$(echo "$1 * -1" | bc)
+		neg=1
+	else
+		val=$1
+		neg=0
+	fi
+
+	if [[ 1 == $(echo "($val / 10^12) >= 1" | bc -l) ]]; then
 		SIZE_T="TB"
-	elif [[ 1 == $(echo "($1 / 10^9) >= 1" | bc -l) ]]; then
+	elif [[ 1 == $(echo "($val / 10^9) >= 1" | bc -l) ]]; then
 		SIZE_T="GB"
-	elif [[ 1 == $(echo "($1 / 10^6) >= 1" | bc -l) ]]; then
+	elif [[ 1 == $(echo "($val / 10^6) >= 1" | bc -l) ]]; then
 		SIZE_T="MB"
-	elif [[ 1 == $(echo "($1 / 1000) >= 1" | bc -l) ]]; then
+	elif [[ 1 == $(echo "($val / 1000) >= 1" | bc -l) ]]; then
 		SIZE_T="KB"
 	else
 		SIZE_T="bytes"
@@ -47,11 +59,10 @@ accurate_sizeof()
 			MAGNITUDE=0
 		;;
 	esac
-	SIZE_VAL=$(echo "$1 / 10^$MAGNITUDE" | bc -l) 
-	printf "$SIZE_VAL $SIZE_T\n"
+	SIZE_VAL=$(echo "$val / 10^$MAGNITUDE" | bc -l) 
+	[[ 1 = $neg ]] && SIZE_VAL=$(echo "$SIZE_VAL * -1" | bc -l)
+	echo -e "$SIZE_VAL $SIZE_T"
 }
-
-
 
 yes_or_no()
 {
@@ -75,12 +86,10 @@ show_master_path()
 			ls -d1 */
 		;;
 		*|"all")
-            [[ 0 = $? ]] &&
-                [[ 0 != $(ls -1 *.7z | wc -l) ]] && 
-                    echo -e "\t${NOC}Archives${BLUE}\n" && ls -1 *.7z
-            [[ 0 = $? ]] &&
-                [[ 0 != $(ls -d1 */ | wc -l) ]] && 
-                    echo -e "\n\t${NOC}Subdirectories${BLUE}\n" && ls -d1 */
+			[[ -n $(ls -1 | grep .7z) ]] && 
+                echo -e "\t${NOC}Archives${BLUE}\n" && ls -1 *.7z
+			[[ -n $(ls -dp1 * | grep /) ]] &&
+   		        echo -e "\n\t${NOC}Subdirectories${BLUE}\n" && ls -d1 */
 		;;
 	esac	
 
@@ -98,6 +107,9 @@ check_exit_status()
 			INTEGRITY)
 				echo -e "${RED}Integrity test has failed, remove this archive and start over.${NOC}"
 			;;
+			PATH)
+				echo -e "${RED}Invalid directory.${NOC}"
+			;;
 		esac
 		exit $exitCode
 	fi
@@ -106,17 +118,31 @@ check_exit_status()
 check_master_path()
 {
 	if [[ -d $MASTER_PATH ]]
-        then
-            cd "$MASTER_PATH"
-            check_exit_status
-            show_master_path $1
-        else
-            echo "That directory does not exist." && exit 1
+	then
+        cd "$MASTER_PATH"
+        check_exit_status PATH
+        show_master_path $1
+    else
+        echo "That directory does not exist." && exit 1
 	fi
 }
 
 print_info()
 {
+	if [[ -n $(ls -1 | grep .7z) ]]
+	then
+		SIZE_ARCHIVES=$(du -bc *.7z | grep total | cut -f1)	
+	else
+		SIZE_ARCHIVES=0
+	fi
+	
+	if [[ -n $(ls -dp1 * | grep /) ]]
+	then
+		SIZE_SUBDIR=$(du -bc */ | grep total | cut -f1)
+	else
+		SIZE_SUBDIR=0
+	fi
+	
 	echo -ne "${CYAN}Subdirectories size\t\t\t:\t\t${NOC}"
 	accurate_sizeof $SIZE_SUBDIR
 
@@ -131,51 +157,60 @@ print_info()
     accurate_sizeof $(du -bs "$MASTER_PATH"/ | cut -f1)
 }
 
-# options used to compress
-DEFAULT_COMPRESS_EXP="7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on "
-[[ -z $2 ]] && MASTER_PATH=$2
+[[ -n $2 ]] && MASTER_PATH=$2
 
 case $1 in
     "-h"|"-help"|"--help")
         echo -e "7zSubComp [ -c [-x -e] -r -v ] [directory A]"
         echo -e "\n7zip subdirectory compressor and subdirectory archive extractor.\n"
         echo -e "   -c --compress       -   enter directory A to compress all subdirectories of A into new archives in A."
-        echo -e "                           Checks archive integrity after creation."
+        echo -e "                           Verifies archive integrity after creation."
         echo -e "   -x -e --extract     -   enter directory A to extract all archives of A into subdirectories in A."
         echo -e "   -r --remove         -   enter directory A to remove all subdirectories of A but save the archives."
         echo -e "   -v --view           -   enter directory A to view all subdirectories and archives of it."
     ;;
     "-v"|"--view")
-        echo -e "${CYAN}Enter a directory to view all subdirectories and archives.${NOC}"
-		echo
-        [[ -z $2 ]] && read -e -p ': ' MASTER_PATH	
- 		check_master_path "all"
-    ;;
-	"-r"|"--remove")
-		echo -e "${CYAN}Enter a directory to remove all separate subdirectories only.
-		\nThis will not remove anything other than sub directories.${NOC}"
-		echo
-        [[ -z $2 ]] && read -e -p ': ' MASTER_PATH
-		
-        TARGETS_NO=$(ls -d1 */ | wc -l)
-		[[ 0 = $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to remove.${NOC}" && exit
+        if [[ -z $2 ]]
+		then
+			echo -e "${CYAN}Enter a directory to view all subdirectories and archives.${NOC}"
+			echo
+        	read -e -p ': ' MASTER_PATH	
+		fi
 		check_master_path "all"
+
+		echo -e "\n${BLUE}Information${NOC}\n-----------"		
+		print_info
+	;;
+	"-r"|"--remove")
+		if [[ -z $2 ]]
+		then
+			echo -e "${CYAN}Enter a directory to remove all separate subdirectories only.
+			\nThis will not remove anything other than sub directories.${NOC}"
+			echo
+			read -e -p ': ' MASTER_PATH
+		fi	
+        
+		check_master_path "all"
+
+		[[ -n $(ls -dp1 * | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
+		[[ -z $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to remove.${NOC}" && exit
+
 		echo -e "\n${GREEN}$TARGETS_NO${NOC} target subdirectories found." 	
 
 		echo -e "\n${RED}Delete${CYAN} all the subdirectories only?${NOC}"
 		if (yes_or_no "$input") then
 			echo -e "\n${RED}Are you sure?${NOC}"
 			if (yes_or_no "$input") then
+	            START_TIME=$SECONDS
 				i=1
 				while [[ 1 = $(echo "$i <= $TARGETS_NO" | bc) ]];
 				do
                     SED_EXP=$i'p'
 					x=$(ls -d1 */ | head -n1)
 					x=${x::-1}
-					echo -e "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]${NOC}"
+					echo -e "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]\t\"$x\"/${NOC}"
 					REMOVAL_EXP="rm -rv \"$x\"/"
 
-					echo $REMOVAL_EXP
 					eval $REMOVAL_EXP
 					
 					((i++))
@@ -183,17 +218,25 @@ case $1 in
 			fi
 		fi
 		show_master_path "all"
+	
+		echo -e "\n${BLUE}Information${NOC}\n-----------"
+		echo -e "${GREEN}$TARGETS_NO${CYAN} archives removed in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
+		print_info
 	;;
     "-x"|"-e"|"--extract") 
-        echo -e "${CYAN}Enter a directory to target and extract all archives into separate subdirectories.
-		\nThis will ${RED}overwrite${CYAN} whatever is already in the subdirectories or create them if they dont exist.${NOC}"
-		echo
-        [[ -z $2 ]] && read -e -p ': ' MASTER_PATH
+   		if [[ -z $2 ]]
+		then
+			echo -e "${CYAN}Enter a directory to target and extract all archives into separate subdirectories.
+			\nThis will ${RED}overwrite${CYAN} whatever is already in the subdirectories or create them if they dont exist.${NOC}"
+			echo
+        	read -e -p ': ' MASTER_PATH
+		fi
 
-		TARGETS_NO=$(ls -1 *.7z | wc -l)
-        [[ 0 = $TARGETS_NO ]] && echo -e "${RED}No archives found inside \"$MASTER_PATH\" to extract.${NOC}" && exit
 		check_master_path "archives"
-        echo -e "\n${GREEN}$TARGETS_NO${NOC} target archives found." 	
+		[[ -n $(ls -1 | grep .7z) ]] && TARGETS_NO=$(ls -1 *.7z | wc -l)
+        [[ -z $TARGETS_NO ]] && echo -e "${RED}No archives found inside \"$MASTER_PATH\" to extract.${NOC}" && exit
+        
+		echo -e "\n${GREEN}$TARGETS_NO${NOC} target archives found." 	
 		
 		echo -e "\n${CYAN}Start extracting?${NOC}"
         if (yes_or_no "$input") then
@@ -202,9 +245,9 @@ case $1 in
             while [[ 1 = $(echo "$i <= $TARGETS_NO" | bc) ]];
             do
                 SED_EXP=$i'p'
-                x=$(ls -d1 *.7z | sed -n "$SED_EXP")
+                x=$(ls -1 *.7z | sed -n "$SED_EXP")
                 EXTRACT_EXP="7z x -y \"$x\""
-				printf "[ $i / $TARGETS_NO ]\t$x\t"
+				echo -ne "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]\t$x\t${NOC}"
 				accurate_sizeof $(du -bs "$x" | cut -f1)
                 
                 echo -e "${CYAN}Extracting archive...${NOC}"
@@ -217,22 +260,23 @@ case $1 in
             
             echo -e "\n${BLUE}Information${NOC}\n-----------"
             echo -e "${GREEN}$TARGETS_NO${CYAN} archives extracted in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
-            SIZE_SUBDIR=$(du -bc */ | grep total | cut -f1)
-            SIZE_ARCHIVES=$(du -bc *.7z | grep total | cut -f1)
 			print_info
 		fi		
     ;;    
     "-c"|"--compress")
 
-        echo -e "${CYAN}Enter a directory to target and compress all subdirectories into separate 7z archives.
-		\nThis will ${RED}overwrite${CYAN} whatever is already in the archives or create them if they dont exist.${NOC}"
-        echo
+   		if [[ -z $2 ]]
+		then
+			echo -e "${CYAN}Enter a directory to target and compress all subdirectories into separate 7z archives.
+			\nThis will ${RED}overwrite${CYAN} whatever is already in the archives or create them if they dont exist.${NOC}"
+        	echo
+			read -e -p ': ' MASTER_PATH
+		fi
 
-        [[ -z $2 ]] && read -e -p ': ' MASTER_PATH
+        check_master_path "subdirs"
+		[[ -n $(ls -dp1 * | grep /) ]] && TARGETS_NO=$(ls -d1 */ | wc -l)
+        [[ -z $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to compress.${NOC}" && exit
 
-        TARGETS_NO=$(ls -d1 */ | wc -l)
-        [[ 0 = $TARGETS_NO ]] && echo -e "${RED}No subdirectories found inside \"$MASTER_PATH\" to compress.${NOC}" && exit
-		check_master_path "subdirs"
         echo -e "\n${GREEN}$TARGETS_NO${NOC} target subdirectories found."
 
         echo -e "\n${CYAN}Current compression settings: ${NOC}$DEFAULT_COMPRESS_EXP"
@@ -247,7 +291,7 @@ case $1 in
                 x=$(ls -d1 */ | sed -n "$SED_EXP")
                 x=${x::-1}
 				
-				printf "[ $i / $TARGETS_NO ]\t$x\t"
+				echo -ne "\n${BLUE}[${NOC}$i${BLUE}/${NOC}$TARGETS_NO${BLUE}]\t$x\t${NOC}"
 				accurate_sizeof $(du -bs "$x"/ | cut -f1)
 
                 COMPRESS_EXP+="\"$x.7z\" \"$x\"/"
@@ -257,7 +301,7 @@ case $1 in
                 eval $COMPRESS_EXP
                 check_exit_status
                 
-                echo -e "${CYAN}Testing integrity of archive...${NOC}"
+                echo -e "\n${CYAN}Verifing integrity of archive...${NOC}"
                 INTEGRITY_EXP="7z t \"$x.7z\""
             
                 echo $INTEGRITY_EXP
@@ -266,11 +310,9 @@ case $1 in
                 
                 ((i++))
             done
-            
+
             echo -e "\n${BLUE}Information${NOC}\n-----------"
-            echo -e "${GREEN}$TARGETS_NO${CYAN} archives successfully created in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
-            SIZE_SUBDIR=$(du -bc */ | grep total | cut -f1)
-            SIZE_ARCHIVES=$(du -bc *.7z | grep total | cut -f1)
+            echo -e "${GREEN}$TARGETS_NO${CYAN} archives created and verified in ${NOC}$((SECONDS - START_TIME))${CYAN} seconds."
 			print_info
             
     	fi
